name: Quality Checks

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml

  prettier:
    uses: ./.github/workflows/prettier.yml
