name: Prettier

on: [workflow_call, workflow_dispatch]

jobs:
  prettier:
    name: Check formatting with Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npx prettier --check .
